### ISSUE TITLE
Iän sijasta voisi kysyä syntymävuotta (koronarokotusaika.sh)

### ISSUE THREAD

**Issue by linjaaho** [oh2fih/Misc-Scripts#1]
Mainio skripti, mutta iän sijasta voisi kysyä syntymävuotta (menevät syntymävuoden mukaan nuo).

**Comment by oh2fih** [comment]
Lämmin kiitos tästä huomiosta! Skripti oli alunperin tehty lähinnä itselleni, joten en tullut ajatelleeksi näin pitkälle.
